### ISSUE TITLE
image compressing

### ISSUE THREAD

**Issue by namishh** [porcelayn/sekiei#11]
in config.toml, i think we can give users the option to set how much they want to reduce the quality of their image, (if they want it). syntax 

```toml
[image]
quality=75 # ranger from 0 to 100. default is 100
```
